//! App asset source: serves the embedded canonical mark SVG (generated by
//! `diktafon --gen-mark` from `mark`) and the bundled Solar icons, falling
//! back to gpui-component's assets for the kit's own icons.

use std::borrow::Cow;

pub struct Assets;

/// App-bundled Solar icons, shadowing nothing in the kit bundle: the
/// `icons/diktafon/` prefix keeps the two sets apart.
#[derive(rust_embed::RustEmbed)]
#[folder = "assets/icons"]
#[prefix = "icons/"]
struct DiktafonIcons;

/// Asset path of the bare mark with transparent holes; render it with
/// `gpui::img(MARK_FLAT)`.
pub const MARK_FLAT: &str = "diktafon-mark-flat.svg";
const MARK_FLAT_BYTES: &[u8] = include_bytes!("../../../assets/diktafon-mark-flat.svg");

impl gpui::AssetSource for Assets {
    fn load(&self, path: &str) -> anyhow::Result<Option<Cow<'static, [u8]>>> {
        if path == MARK_FLAT {
            return Ok(Some(Cow::Borrowed(MARK_FLAT_BYTES)));
        }
        if let Some(file) = DiktafonIcons::get(path) {
            return Ok(Some(file.data));
        }
        gpui_component_assets::Assets.load(path)
    }

    fn list(&self, path: &str) -> anyhow::Result<Vec<gpui::SharedString>> {
        let mut entries: Vec<gpui::SharedString> = DiktafonIcons::iter()
            .filter(|entry| entry.starts_with(path))
            .map(gpui::SharedString::from)
            .collect();
        entries.extend(gpui_component_assets::Assets.list(path)?);
        Ok(entries)
    }
}

#[cfg(test)]
mod tests {
    use super::*;
    use crate::icons::DiktafonIcon;
    use gpui::AssetSource;
    use gpui_component::IconNamed;

    #[test]
    fn every_icon_is_bundled() {
        let bundled = DiktafonIcons::iter()
            .filter(|path| path.starts_with("icons/diktafon/"))
            .count();
        assert_eq!(
            bundled,
            DiktafonIcon::ALL.len(),
            "icon list and bundle differ"
        );
        for icon in DiktafonIcon::ALL {
            let path = icon.path();
            assert!(
                Assets.load(&path).is_ok_and(|data| data.is_some()),
                "missing {path}"
            );
        }
    }

    #[test]
    fn kit_icons_still_resolve_through_the_fallback() {
        assert!(
            Assets
                .load("icons/check.svg")
                .is_ok_and(|data| data.is_some())
        );
    }
}
