//! App asset source: serves the embedded canonical mark SVG (generated by
//! `diktafon --gen-mark` from `mark`) and falls back to gpui-component's
//! assets for the kit's icons.

use std::borrow::Cow;

pub struct Assets;

/// Asset path of the bare mark with transparent holes; render it with
/// `gpui::img(MARK_FLAT)`.
pub const MARK_FLAT: &str = "diktafon-mark-flat.svg";
const MARK_FLAT_BYTES: &[u8] = include_bytes!("../../../assets/diktafon-mark-flat.svg");

impl gpui::AssetSource for Assets {
    fn load(&self, path: &str) -> anyhow::Result<Option<Cow<'static, [u8]>>> {
        if path == MARK_FLAT {
            return Ok(Some(Cow::Borrowed(MARK_FLAT_BYTES)));
        }
        gpui_component_assets::Assets.load(path)
    }

    fn list(&self, path: &str) -> anyhow::Result<Vec<gpui::SharedString>> {
        gpui_component_assets::Assets.list(path)
    }
}
